{
	"name": "RedQueen",
	"version": "1.0.33",
	"icon": "fas fa-biohazard",
	"category": "alice",
	"author": "ProjectAlice",
	"maintainers": [
		"Psycho",
		"maxbachmann",
		"lazza"
	],
	"desc": "Red Queen is the official Project Alice personality skill",
	"aliceMinVersion": "1.0.0-b4",
    "systemRequirements": [],
    "pipRequirements": [],
    "conditions": {
        "lang": [
            "en",
            "fr",
            "de",
            "it",
            "pl"
        ]
    }
}
